import { motion } from 'framer-motion';
import { ArrowRight, Boxes, Compass, FolderPlus, Gamepad2, Library, Play, Search, Settings2, ShieldCheck, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useCurrentUser, useIsAuthenticated } from '@/stores/authStore';
import { useInstanceStore } from '@/stores/instanceStore';
import { toIconSrc } from '@/lib/icon-src';

function relativeDate(value?: string) {
  if (!value) return 'Ещё не запускалась';
  const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86_400_000));
  return days === 0 ? 'Запускалась сегодня' : days === 1 ? 'Запускалась вчера' : `Запускалась ${days} дн. назад`;
}

export function HomePage() {
  const navigate = useNavigate();
  const user = useCurrentUser();
  const signedIn = useIsAuthenticated();
  const instances = useInstanceStore(state => state.instances);
  const recent = [...instances].sort((a, b) => new Date(b.lastPlayed || b.createdAt).getTime() - new Date(a.lastPlayed || a.createdAt).getTime()).slice(0, 4);
  const playHours = Math.round(instances.reduce((sum, item) => sum + (item.totalPlayTime || 0), 0) / 60);

  return <div className="h-full overflow-y-auto px-5 py-5 sm:px-7 sm:py-7">
    <div className="mx-auto max-w-6xl space-y-5">
      <motion.section initial={{ opacity:0, y:12 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.24 }} className="relative overflow-hidden rounded-[24px] p-6 sm:p-8" style={{ background:'linear-gradient(135deg, var(--color-surface), color-mix(in srgb, var(--color-surface-2) 82%, var(--color-primary) 18%))', border:'1px solid var(--color-border)', boxShadow:'var(--shadow-md)' }}>
        <div aria-hidden className="pointer-events-none absolute -right-20 -top-28 h-72 w-72 rounded-full" style={{ background:'radial-gradient(circle, color-mix(in srgb, var(--color-primary) 26%, transparent), transparent 68%)', filter:'blur(15px)' }} />
        <div className="relative flex flex-col justify-between gap-7 lg:flex-row lg:items-end">
          <div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.14em]" style={{ background:'var(--color-primary-dim)', color:'var(--color-primary)', border:'1px solid color-mix(in srgb, var(--color-primary) 45%, var(--color-border))' }}><Sparkles className="h-3.5 w-3.5" />Ваше игровое пространство</span><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl" style={{ color:'var(--color-text)' }}>{signedIn ? `С возвращением, ${user?.username || 'игрок'}` : 'Ваш Minecraft — под контролем'}</h1><p className="mt-3 max-w-xl text-sm leading-relaxed" style={{ color:'var(--color-text-secondary)' }}>{signedIn ? 'Откройте недавнюю сборку, подготовьте новую или найдите проект. Лаунчер покажет реальное состояние файлов до установки.' : 'Войдите в игровой аккаунт, затем создайте или импортируйте первую сборку.'}</p><div className="mt-6 flex flex-wrap gap-2.5"><button onClick={() => navigate(signedIn ? '/library' : '/settings/account')} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold" style={{ background:'var(--color-primary)', color:'var(--color-primary-text)', boxShadow:'var(--shadow-glow)' }}>{signedIn ? <><Play className="h-4 w-4 fill-current" />Открыть сборки</> : <><ShieldCheck className="h-4 w-4" />Войти в аккаунт</>}</button><button onClick={() => navigate('/library?create=1')} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold" style={{ background:'var(--color-surface-active)', color:'var(--color-text)', border:'1px solid var(--color-border)' }}><FolderPlus className="h-4 w-4" />Новая сборка</button><button onClick={() => navigate('/discover')} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold" style={{ background:'var(--color-surface-active)', color:'var(--color-text)', border:'1px solid var(--color-border)' }}><Compass className="h-4 w-4" />Discover</button></div></div>
          <div className="grid min-w-[280px] grid-cols-3 gap-2">{[{ icon:Library, value:String(instances.length), label:'Сборок' }, { icon:Gamepad2, value:playHours ? `${playHours} ч` : '—', label:'В игре' }, { icon:Boxes, value:instances.filter(item => item.lastPlayed).length, label:'Активных' }].map(stat => <div key={stat.label} className="rounded-2xl p-3" style={{ background:'color-mix(in srgb, var(--color-surface) 70%, transparent)', border:'1px solid var(--color-border)' }}><stat.icon className="mb-3 h-4 w-4" style={{ color:'var(--color-primary)' }} /><p className="text-sm font-black" style={{ color:'var(--color-text)' }}>{stat.value}</p><p className="mt-0.5 text-[10px] font-semibold" style={{ color:'var(--color-text-tertiary)' }}>{stat.label}</p></div>)}</div>
        </div>
      </motion.section>

      <section className="grid gap-3 md:grid-cols-3">{[{ icon:Search, title:'Найти проект', text:'Поиск модов, модпаков, наборов ресурсов и шейдеров.', to:'/discover' }, { icon:Library, title:'Импортировать сборку', text:'MRPACK, ZIP и поддерживаемые лаунчеры с проверкой manifest.', to:'/library?create=1' }, { icon:Settings2, title:'Настроить лаунчер', text:'Тема, Java, управление и поведение интерфейса.', to:'/settings' }].map(action => <button key={action.title} onClick={() => navigate(action.to)} className="group flex items-start gap-3 rounded-2xl p-4 text-left transition-transform hover:-translate-y-0.5" style={{ background:'var(--color-surface)', border:'1px solid var(--color-border)' }}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl" style={{ background:'var(--color-primary-dim)', color:'var(--color-primary)' }}><action.icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-black" style={{ color:'var(--color-text)' }}>{action.title}</span><span className="mt-1 block text-[11px] leading-relaxed" style={{ color:'var(--color-text-secondary)' }}>{action.text}</span></span><ArrowRight className="mt-1 h-4 w-4 opacity-0 transition-opacity group-hover:opacity-100" style={{ color:'var(--color-primary)' }} /></button>)}</section>

      <section className="rounded-[22px] p-5" style={{ background:'var(--color-surface)', border:'1px solid var(--color-border)' }}><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em]" style={{ color:'var(--color-primary)' }}>Библиотека</p><h2 className="mt-1 text-lg font-black" style={{ color:'var(--color-text)' }}>{recent.length ? 'Недавние сборки' : 'Пока нет сборок'}</h2></div><button onClick={() => navigate('/library')} className="inline-flex items-center gap-1 text-xs font-bold" style={{ color:'var(--color-primary)' }}>Открыть библиотеку <ArrowRight className="h-3.5 w-3.5" /></button></div>{recent.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{recent.map(instance => <button key={instance.id} onClick={() => navigate('/library')} className="group overflow-hidden rounded-2xl p-3 text-left transition-transform hover:-translate-y-0.5" style={{ background:'var(--color-surface-2)', border:'1px solid var(--color-border)' }}><div className="flex items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-xl text-sm font-black" style={{ background:instance.color ? `${instance.color}20` : 'var(--color-surface)', color:instance.color || 'var(--color-primary)' }}>{instance.iconPath ? <img src={toIconSrc(instance.iconPath)} className="h-full w-full object-cover" alt="" /> : instance.name.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black" style={{ color:'var(--color-text)' }}>{instance.name}</p><p className="mt-0.5 truncate text-[10px]" style={{ color:'var(--color-text-secondary)' }}>{instance.minecraftVersion} · {instance.modLoader}</p></div></div><p className="mt-3 text-[10px]" style={{ color:'var(--color-text-tertiary)' }}>{relativeDate(instance.lastPlayed)}</p></button>)}</div> : <div className="rounded-2xl border border-dashed p-8 text-center" style={{ borderColor:'var(--color-border)', background:'var(--color-surface-2)' }}><Library className="mx-auto h-7 w-7" style={{ color:'var(--color-primary)' }} /><p className="mt-3 text-sm font-black" style={{ color:'var(--color-text)' }}>Создайте или импортируйте первую сборку</p><p className="mx-auto mt-1 max-w-md text-xs leading-relaxed" style={{ color:'var(--color-text-secondary)' }}>После импорта лаунчер покажет состав manifest до установки и сохранит реальные иконку и изображения сборки.</p><button onClick={() => navigate('/library?create=1')} className="mt-4 inline-flex items-center gap-2 rounded-xl px-4 py-2 text-xs font-bold" style={{ background:'var(--color-primary)', color:'var(--color-primary-text)' }}><FolderPlus className="h-3.5 w-3.5" />Создать сборку</button></div>}</section>
    </div>
  </div>;
}
