import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, Check, Compass, HardDrive, Languages, LayoutDashboard, Library, PanelTop, ShieldCheck, Sparkles, X } from 'lucide-react';
import { invoke } from '@/lib/invoke-shim';
import { useLanguageStore, type Lang } from '@/stores/languageStore';
import { useUiStore, type UiMode } from '@/stores/uiStore';
import { MicrosoftAuthOAuth } from '@/components/auth/MicrosoftAuthOAuth';

const SETUP_KEY = 'portal-first-launch-complete-v1';
const TUTORIAL_KEY = 'portal-interface-tutorial-complete-v1';
const BASE_LAUNCHER_BYTES = 15.3 * 1024 * 1024;
const bytes = (value?: number) => value === undefined || value === null ? 'Недоступно' : value < 1024 * 1024 ? `${Math.max(1, Math.round(value / 1024))} КБ` : value < 1024 ** 3 ? `${(value / 1024 ** 2).toFixed(1).replace('.', ',')} МБ` : `${(value / 1024 ** 3).toFixed(1).replace('.', ',')} ГБ`;
type StorageOverview = { launcherPath: string; usedBytes: number; launcherBytes?: number; totalBytes?: number; freeBytes?: number | null };

function Tutorial({ onClose }: { onClose: () => void }) {
  const [page, setPage] = useState(0);
  const cards = [
    { icon: LayoutDashboard, title: 'Главная', text: 'Недавние сборки, быстрые действия и настоящее состояние библиотеки.' },
    { icon: Library, title: 'Библиотека', text: 'Создавайте, импортируйте и настраивайте сборки с предварительным просмотром manifest.' },
    { icon: Compass, title: 'Discover', text: 'Находите моды, модпаки, shaderpacks и наборы ресурсов для выбранной сборки.' },
    { icon: PanelTop, title: 'Навигация', text: 'Notch Panel и Sidebar настраиваются отдельно в оформлении, но используют один стиль.' },
  ];
  const card = cards[page]; const Icon = card.icon;
  return <motion.div className="fixed inset-0 z-[220] grid place-items-center p-5" style={{ background: 'color-mix(in srgb, var(--color-bg) 82%, rgba(0,0,0,0.72))', backdropFilter: 'blur(12px)' }} initial={{ opacity: 0 }} animate={{ opacity: 1 }}><motion.section className="w-full max-w-xl rounded-[32px] p-6 sm:p-8" style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', boxShadow: 'var(--shadow-lg)' }} initial={{ opacity: 0, y: 16, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }}><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[0.16em]" style={{ color: 'var(--color-primary)' }}>Короткий тур · {page + 1}/{cards.length}</span><button type="button" onClick={onClose} className="rounded-xl p-2" style={{ background: 'var(--color-surface-2)', color: 'var(--color-text-secondary)' }}><X className="h-4 w-4" /></button></div><div className="mt-8 flex min-h-60 flex-col items-center justify-center rounded-[28px] p-7 text-center" style={{ background: 'radial-gradient(circle at 50% 0%, var(--color-primary-dim), var(--color-surface-2) 66%)', border: '1px solid var(--color-border)' }}><span className="grid h-20 w-20 place-items-center rounded-full" style={{ background: 'var(--color-primary)', color: 'var(--color-primary-text)', boxShadow: 'var(--shadow-glow)' }}><Icon className="h-9 w-9" /></span><h2 className="mt-5 text-2xl font-black" style={{ color: 'var(--color-text)' }}>{card.title}</h2><p className="mt-2 max-w-sm text-sm leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>{card.text}</p></div><div className="mt-6 flex items-center justify-between"><div className="flex gap-1.5">{cards.map((_, index) => <span key={index} className="h-1.5 rounded-full transition-all" style={{ width: index === page ? 24 : 7, background: index === page ? 'var(--color-primary)' : 'var(--color-border)' }} />)}</div><button type="button" onClick={() => page === cards.length - 1 ? onClose() : setPage(value => value + 1)} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black" style={{ background: 'var(--color-primary)', color: 'var(--color-primary-text)' }}>{page === cards.length - 1 ? 'Начать работу' : 'Далее'} <ArrowRight className="h-4 w-4" /></button></div></motion.section></motion.div>;
}

function StyleChoice({ mode, active, onSelect }: { mode: UiMode; active: boolean; onSelect: () => void }) {
  const modern = mode === 'new';
  return <button type="button" onClick={onSelect} className="relative overflow-hidden rounded-2xl p-3 text-left transition-transform duration-150 hover:-translate-y-0.5 active:scale-[0.99]" style={{ background: active ? 'var(--color-primary-dim)' : 'var(--color-surface)', border: `1px solid ${active ? 'var(--color-primary)' : 'var(--color-border)'}` }}><span aria-hidden className="absolute -right-5 -top-5 h-16 w-16 rounded-full" style={{ background: modern ? 'color-mix(in srgb, var(--color-primary) 20%, transparent)' : 'var(--color-surface-2)' }} /><span className="relative flex items-center justify-between"><span className="text-xs font-black" style={{ color: 'var(--color-text)' }}>{modern ? 'Новый' : 'Классический'}</span>{active && <Check className="h-4 w-4" style={{ color: 'var(--color-primary)' }} />}</span><span className="relative mt-3 block rounded-lg p-2" style={{ background: modern ? 'color-mix(in srgb, var(--color-surface-2) 74%, transparent)' : 'var(--color-surface-2)', border: modern ? '1px solid color-mix(in srgb, var(--color-primary) 30%, transparent)' : '1px solid var(--color-border)' }}><span className="block h-1.5 w-8 rounded-full" style={{ background: modern ? 'var(--color-primary)' : 'var(--color-text-tertiary)' }} /><span className="mt-2 grid grid-cols-3 gap-1"><i className="h-4 rounded" style={{ background: modern ? 'var(--color-primary-dim)' : 'var(--color-surface)' }} /><i className="h-4 rounded" style={{ background: 'var(--color-surface)' }} /><i className="h-4 rounded" style={{ background: 'var(--color-surface)' }} /></span></span><span className="relative mt-2 block text-[10px] leading-4" style={{ color: 'var(--color-text-secondary)' }}>{modern ? 'Мягкие поверхности, акцентные контуры и плавные переходы.' : 'Строгие поверхности и компактная привычная компоновка.'}</span></button>;
}

export function FirstLaunchExperience() {
  const lang = useLanguageStore(state => state.lang); const setLang = useLanguageStore(state => state.setLang);
  const uiMode = useUiStore(state => state.uiMode); const setUi = useUiStore(state => state.set);
  const [mode, setMode] = useState<'checking' | 'setup' | 'tutorial' | 'none'>(() => localStorage.getItem(SETUP_KEY) ? (localStorage.getItem(TUTORIAL_KEY) ? 'none' : 'tutorial') : 'checking');
  const [step, setStep] = useState(0); const [storage, setStorage] = useState<StorageOverview | null>(null);
  useEffect(() => { if (mode !== 'checking') return; void invoke<StorageOverview>('get_launcher_storage_overview').then(overview => { setStorage(overview); setMode(overview.usedBytes === 0 ? 'setup' : 'none'); }).catch(() => setMode('none')); }, [mode]);
  const finishSetup = () => { localStorage.setItem(SETUP_KEY, '1'); setMode('tutorial'); };
  const finishTutorial = () => { localStorage.setItem(TUTORIAL_KEY, '1'); setMode('none'); };
  if (mode === 'checking' || mode === 'none') return null;
  if (mode === 'tutorial') return <Tutorial onClose={finishTutorial} />;
  const setStyle = (value: UiMode) => { setUi('uiMode', value); setUi('panelVersion', value); };
  const totalBytes = storage?.totalBytes ?? (storage?.usedBytes ?? 0) + (storage?.launcherBytes ?? BASE_LAUNCHER_BYTES);
  return <AnimatePresence><motion.div className="fixed inset-0 z-[230] grid place-items-center overflow-y-auto p-5" style={{ background: 'radial-gradient(circle at 12% 5%, var(--color-primary-dim), transparent 28%), var(--color-bg)', color: 'var(--color-text)' }} initial={{ opacity: 0 }} animate={{ opacity: 1 }}><motion.section className="my-auto w-full max-w-3xl overflow-hidden rounded-[34px]" style={{ background: 'color-mix(in srgb, var(--color-surface) 94%, transparent)', border: '1px solid var(--color-border)', boxShadow: 'var(--shadow-lg)' }} initial={{ opacity: 0, y: 18, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }}><div className="h-1.5" style={{ background: 'linear-gradient(90deg, var(--color-primary), color-mix(in srgb, var(--color-primary) 20%, transparent))' }} /><div className="p-6 sm:p-8"><div className="flex items-center justify-between"><div className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[10px] font-black uppercase tracking-[0.15em]" style={{ background: 'var(--color-primary-dim)', color: 'var(--color-primary)' }}><Sparkles className="h-3.5 w-3.5" />Portal Launcher · первый запуск</div><span className="text-xs font-bold" style={{ color: 'var(--color-text-tertiary)' }}>{step + 1} / 3</span></div>
    {step === 0 && <div className="mt-8 grid gap-7 md:grid-cols-[1.1fr_.9fr]"><div><h1 className="text-3xl font-black tracking-tight">Minecraft без лишних шагов</h1><p className="mt-3 text-sm leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>Portal Launcher хранит сборки, проверяет manifest перед установкой, управляет модами и не скрывает состояние файлов.</p><div className="mt-6 grid grid-cols-3 gap-2">{['Сборки', 'Discover', 'Файлы'].map((item, index) => <div key={item} className="rounded-2xl p-3" style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)' }}><span className="text-[10px] font-black" style={{ color: 'var(--color-primary)' }}>0{index + 1}</span><p className="mt-4 text-xs font-black">{item}</p></div>)}</div></div><div className="space-y-3"><div className="rounded-[26px] p-5" style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)' }}><Languages className="h-6 w-6" style={{ color: 'var(--color-primary)' }} /><h2 className="mt-4 text-lg font-black">Язык интерфейса</h2><div className="mt-4 grid gap-2">{([['ru', 'Русский'], ['en', 'English']] as [Lang, string][]).map(([value, label]) => <button type="button" key={value} onClick={() => setLang(value)} className="flex items-center justify-between rounded-xl px-4 py-3 text-left text-sm font-bold" style={{ background: lang === value ? 'var(--color-primary-dim)' : 'var(--color-surface)', color: 'var(--color-text)', border: `1px solid ${lang === value ? 'var(--color-primary)' : 'var(--color-border)'}` }}>{label}{lang === value && <Check className="h-4 w-4" style={{ color: 'var(--color-primary)' }} />}</button>)}</div></div><div className="rounded-[26px] p-4" style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)' }}><p className="text-sm font-black">Стиль интерфейса</p><p className="mt-1 text-[11px]" style={{ color: 'var(--color-text-secondary)' }}>Его можно изменить в самом низу «Оформления» в любое время.</p><div className="mt-3 grid grid-cols-2 gap-2"><StyleChoice mode="new" active={uiMode === 'new'} onSelect={() => setStyle('new')} /><StyleChoice mode="old" active={uiMode === 'old'} onSelect={() => setStyle('old')} /></div></div></div></div>}
    {step === 1 && <div className="mt-8 grid gap-6 md:grid-cols-2"><div><HardDrive className="h-8 w-8" style={{ color: 'var(--color-primary)' }} /><h1 className="mt-4 text-3xl font-black">Место на диске</h1><p className="mt-3 text-sm leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>Показаны размер самого Portal Launcher и данные в его папке: кэш, Java и ваши сборки.</p></div><div className="space-y-3 rounded-[26px] p-5" style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)' }}><div className="rounded-2xl p-4" style={{ background: 'var(--color-surface)' }}><p className="text-[10px] font-black uppercase tracking-[0.14em]" style={{ color: 'var(--color-text-tertiary)' }}>Portal Launcher и данные</p><p className="mt-1 text-2xl font-black">{bytes(totalBytes)}</p><p className="mt-1 text-[10px]" style={{ color: 'var(--color-text-tertiary)' }}>Сам лаунчер занимает 15,3 МБ. После установки Java, игры и сборок общий размер будет увеличиваться.</p></div><div className="grid grid-cols-2 gap-2"><div className="rounded-2xl p-3" style={{ background: 'var(--color-surface)' }}><p className="text-[9px] font-black uppercase tracking-[0.1em]" style={{ color: 'var(--color-text-tertiary)' }}>Данные и кэш</p><p className="mt-1 text-sm font-black">{bytes(storage?.usedBytes)}</p></div><div className="rounded-2xl p-3" style={{ background: 'var(--color-surface)' }}><p className="text-[9px] font-black uppercase tracking-[0.1em]" style={{ color: 'var(--color-text-tertiary)' }}>Свободно</p><p className="mt-1 text-sm font-black">{bytes(storage?.freeBytes ?? undefined)}</p></div></div>{storage?.launcherPath && <p className="truncate text-[10px]" style={{ color: 'var(--color-text-tertiary)' }}>{storage.launcherPath}</p>}</div></div>}
    {step === 2 && <div className="mt-8"><div className="mx-auto max-w-lg text-center"><ShieldCheck className="mx-auto h-8 w-8" style={{ color: 'var(--color-primary)' }} /><h1 className="mt-4 text-3xl font-black">Войдите в игру</h1><p className="mt-2 text-sm" style={{ color: 'var(--color-text-secondary)' }}>Microsoft и Ely.by используют уже существующий безопасный вход лаунчера. Его можно пропустить и сделать позже.</p></div><div className="mx-auto mt-5 max-w-md rounded-[26px] p-3" style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)' }}><MicrosoftAuthOAuth onSuccess={finishSetup} onCancel={() => {}} /></div></div>}
    <footer className="mt-7 flex items-center justify-between gap-3"><button type="button" onClick={() => step > 0 && setStep(value => value - 1)} className="rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-0" style={{ color: 'var(--color-text-secondary)' }} disabled={step === 0}>Назад</button>{step < 2 ? <button type="button" onClick={() => setStep(value => value + 1)} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black" style={{ background: 'var(--color-primary)', color: 'var(--color-primary-text)' }}>Далее <ArrowRight className="h-4 w-4" /></button> : <button type="button" onClick={finishSetup} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black" style={{ background: 'var(--color-primary)', color: 'var(--color-primary-text)' }}>Продолжить без входа <ArrowRight className="h-4 w-4" /></button>}</footer></div></motion.section></motion.div></AnimatePresence>;
}
